spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    console: true
    path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  banner:
    location: springbanner.txt